//! Physical key codes of each platform mapped to W3C `KeyboardEvent.code` names.
//! Never goes through the keyboard layout, so it is safe off the main thread.

pub const UNIDENTIFIED: &str = "Unidentified";

/// macOS virtual key code (`kVK_*`, layout independent) to W3C code.
pub fn mac(keycode: u16) -> &'static str {
    match keycode {
        0x00 => "KeyA",
        0x01 => "KeyS",
        0x02 => "KeyD",
        0x03 => "KeyF",
        0x04 => "KeyH",
        0x05 => "KeyG",
        0x06 => "KeyZ",
        0x07 => "KeyX",
        0x08 => "KeyC",
        0x09 => "KeyV",
        0x0A => "IntlBackslash",
        0x0B => "KeyB",
        0x0C => "KeyQ",
        0x0D => "KeyW",
        0x0E => "KeyE",
        0x0F => "KeyR",
        0x10 => "KeyY",
        0x11 => "KeyT",
        0x12 => "Digit1",
        0x13 => "Digit2",
        0x14 => "Digit3",
        0x15 => "Digit4",
        0x16 => "Digit6",
        0x17 => "Digit5",
        0x18 => "Equal",
        0x19 => "Digit9",
        0x1A => "Digit7",
        0x1B => "Minus",
        0x1C => "Digit8",
        0x1D => "Digit0",
        0x1E => "BracketRight",
        0x1F => "KeyO",
        0x20 => "KeyU",
        0x21 => "BracketLeft",
        0x22 => "KeyI",
        0x23 => "KeyP",
        0x24 => "Enter",
        0x25 => "KeyL",
        0x26 => "KeyJ",
        0x27 => "Quote",
        0x28 => "KeyK",
        0x29 => "Semicolon",
        0x2A => "Backslash",
        0x2B => "Comma",
        0x2C => "Slash",
        0x2D => "KeyN",
        0x2E => "KeyM",
        0x2F => "Period",
        0x30 => "Tab",
        0x31 => "Space",
        0x32 => "Backquote",
        0x33 => "Backspace",
        0x35 => "Escape",
        0x36 => "MetaRight",
        0x37 => "MetaLeft",
        0x38 => "ShiftLeft",
        0x39 => "CapsLock",
        0x3A => "AltLeft",
        0x3B => "ControlLeft",
        0x3C => "ShiftRight",
        0x3D => "AltRight",
        0x3E => "ControlRight",
        0x3F => "Fn",
        0x40 => "F17",
        0x41 => "NumpadDecimal",
        0x43 => "NumpadMultiply",
        0x45 => "NumpadAdd",
        0x47 => "NumLock",
        0x48 => "AudioVolumeUp",
        0x49 => "AudioVolumeDown",
        0x4A => "AudioVolumeMute",
        0x4B => "NumpadDivide",
        0x4C => "NumpadEnter",
        0x4E => "NumpadSubtract",
        0x4F => "F18",
        0x50 => "F19",
        0x51 => "NumpadEqual",
        0x52 => "Numpad0",
        0x53 => "Numpad1",
        0x54 => "Numpad2",
        0x55 => "Numpad3",
        0x56 => "Numpad4",
        0x57 => "Numpad5",
        0x58 => "Numpad6",
        0x59 => "Numpad7",
        0x5A => "F20",
        0x5B => "Numpad8",
        0x5C => "Numpad9",
        0x5D => "IntlYen",
        0x5E => "IntlRo",
        0x5F => "NumpadComma",
        0x60 => "F5",
        0x61 => "F6",
        0x62 => "F7",
        0x63 => "F3",
        0x64 => "F8",
        0x65 => "F9",
        0x66 => "Lang2",
        0x67 => "F11",
        0x68 => "Lang1",
        0x69 => "F13",
        0x6A => "F16",
        0x6B => "F14",
        0x6D => "F10",
        0x6E => "ContextMenu",
        0x6F => "F12",
        0x71 => "F15",
        0x72 => "Insert",
        0x73 => "Home",
        0x74 => "PageUp",
        0x75 => "Delete",
        0x76 => "F4",
        0x77 => "End",
        0x78 => "F2",
        0x79 => "PageDown",
        0x7A => "F1",
        0x7B => "ArrowLeft",
        0x7C => "ArrowRight",
        0x7D => "ArrowDown",
        0x7E => "ArrowUp",
        _ => UNIDENTIFIED,
    }
}

/// Windows low-level hook key: set-1 scan code, the extended (E0) flag and the
/// virtual-key code (used only where scan codes are ambiguous).
/// Returns `None` for synthetic events that must not be counted (fake shifts).
#[cfg_attr(not(windows), allow(dead_code))]
pub fn windows(scan: u32, extended: bool, vk: u32) -> Option<&'static str> {
    match vk {
        0x13 => return Some("Pause"),
        0x90 => return Some("NumLock"),
        0x2C => return Some("PrintScreen"),
        _ => {}
    }
    Some(match (scan, extended) {
        // E0 2A / E0 AA are "fake shifts" around navigation keys, not real presses.
        (0x2A, true) => return None,
        (0x01, _) => "Escape",
        (0x02, _) => "Digit1",
        (0x03, _) => "Digit2",
        (0x04, _) => "Digit3",
        (0x05, _) => "Digit4",
        (0x06, _) => "Digit5",
        (0x07, _) => "Digit6",
        (0x08, _) => "Digit7",
        (0x09, _) => "Digit8",
        (0x0A, _) => "Digit9",
        (0x0B, _) => "Digit0",
        (0x0C, _) => "Minus",
        (0x0D, _) => "Equal",
        (0x0E, _) => "Backspace",
        (0x0F, _) => "Tab",
        (0x10, true) => "MediaTrackPrevious",
        (0x10, false) => "KeyQ",
        (0x11, _) => "KeyW",
        (0x12, _) => "KeyE",
        (0x13, _) => "KeyR",
        (0x14, _) => "KeyT",
        (0x15, _) => "KeyY",
        (0x16, _) => "KeyU",
        (0x17, _) => "KeyI",
        (0x18, _) => "KeyO",
        (0x19, true) => "MediaTrackNext",
        (0x19, false) => "KeyP",
        (0x1A, _) => "BracketLeft",
        (0x1B, _) => "BracketRight",
        (0x1C, true) => "NumpadEnter",
        (0x1C, false) => "Enter",
        (0x1D, true) => "ControlRight",
        (0x1D, false) => "ControlLeft",
        (0x1E, _) => "KeyA",
        (0x1F, _) => "KeyS",
        (0x20, true) => "AudioVolumeMute",
        (0x20, false) => "KeyD",
        (0x21, _) => "KeyF",
        (0x22, true) => "MediaPlayPause",
        (0x22, false) => "KeyG",
        (0x23, _) => "KeyH",
        (0x24, true) => "MediaStop",
        (0x24, false) => "KeyJ",
        (0x25, _) => "KeyK",
        (0x26, _) => "KeyL",
        (0x27, _) => "Semicolon",
        (0x28, _) => "Quote",
        (0x29, _) => "Backquote",
        (0x2A, false) => "ShiftLeft",
        (0x2B, _) => "Backslash",
        (0x2C, _) => "KeyZ",
        (0x2D, _) => "KeyX",
        (0x2E, true) => "AudioVolumeDown",
        (0x2E, false) => "KeyC",
        (0x2F, _) => "KeyV",
        (0x30, true) => "AudioVolumeUp",
        (0x30, false) => "KeyB",
        (0x31, _) => "KeyN",
        (0x32, _) => "KeyM",
        (0x33, _) => "Comma",
        (0x34, _) => "Period",
        (0x35, true) => "NumpadDivide",
        (0x35, false) => "Slash",
        // Right Shift reports the extended flag in some hook setups; it is 0x36 either way.
        (0x36, _) => "ShiftRight",
        (0x37, true) => "PrintScreen",
        (0x37, false) => "NumpadMultiply",
        (0x38, true) => "AltRight",
        (0x38, false) => "AltLeft",
        (0x39, _) => "Space",
        (0x3A, _) => "CapsLock",
        (0x3B, _) => "F1",
        (0x3C, _) => "F2",
        (0x3D, _) => "F3",
        (0x3E, _) => "F4",
        (0x3F, _) => "F5",
        (0x40, _) => "F6",
        (0x41, _) => "F7",
        (0x42, _) => "F8",
        (0x43, _) => "F9",
        (0x44, _) => "F10",
        (0x45, _) => "NumLock",
        (0x46, _) => "ScrollLock",
        (0x47, true) => "Home",
        (0x47, false) => "Numpad7",
        (0x48, true) => "ArrowUp",
        (0x48, false) => "Numpad8",
        (0x49, true) => "PageUp",
        (0x49, false) => "Numpad9",
        (0x4A, _) => "NumpadSubtract",
        (0x4B, true) => "ArrowLeft",
        (0x4B, false) => "Numpad4",
        (0x4C, _) => "Numpad5",
        (0x4D, true) => "ArrowRight",
        (0x4D, false) => "Numpad6",
        (0x4E, _) => "NumpadAdd",
        (0x4F, true) => "End",
        (0x4F, false) => "Numpad1",
        (0x50, true) => "ArrowDown",
        (0x50, false) => "Numpad2",
        (0x51, true) => "PageDown",
        (0x51, false) => "Numpad3",
        (0x52, true) => "Insert",
        (0x52, false) => "Numpad0",
        (0x53, true) => "Delete",
        (0x53, false) => "NumpadDecimal",
        (0x56, _) => "IntlBackslash",
        (0x57, _) => "F11",
        (0x58, _) => "F12",
        (0x5B, true) => "MetaLeft",
        (0x5C, true) => "MetaRight",
        (0x5D, true) => "ContextMenu",
        (0x64, _) => "F13",
        (0x65, _) => "F14",
        (0x66, _) => "F15",
        (0x67, _) => "F16",
        (0x68, _) => "F17",
        (0x69, _) => "F18",
        (0x6A, _) => "F19",
        (0x6B, _) => "F20",
        (0x6C, _) => "F21",
        (0x6D, _) => "F22",
        (0x6E, _) => "F23",
        (0x70, _) => "KanaMode",
        (0x73, _) => "IntlRo",
        (0x76, _) => "F24",
        (0x79, _) => "Convert",
        (0x7B, _) => "NonConvert",
        (0x7D, _) => "IntlYen",
        (0x7E, _) => "NumpadComma",
        _ => UNIDENTIFIED,
    })
}

/// Linux evdev key code (X11 keycode minus 8) to W3C code.
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
pub fn evdev(code: u32) -> &'static str {
    match code {
        1 => "Escape",
        2 => "Digit1",
        3 => "Digit2",
        4 => "Digit3",
        5 => "Digit4",
        6 => "Digit5",
        7 => "Digit6",
        8 => "Digit7",
        9 => "Digit8",
        10 => "Digit9",
        11 => "Digit0",
        12 => "Minus",
        13 => "Equal",
        14 => "Backspace",
        15 => "Tab",
        16 => "KeyQ",
        17 => "KeyW",
        18 => "KeyE",
        19 => "KeyR",
        20 => "KeyT",
        21 => "KeyY",
        22 => "KeyU",
        23 => "KeyI",
        24 => "KeyO",
        25 => "KeyP",
        26 => "BracketLeft",
        27 => "BracketRight",
        28 => "Enter",
        29 => "ControlLeft",
        30 => "KeyA",
        31 => "KeyS",
        32 => "KeyD",
        33 => "KeyF",
        34 => "KeyG",
        35 => "KeyH",
        36 => "KeyJ",
        37 => "KeyK",
        38 => "KeyL",
        39 => "Semicolon",
        40 => "Quote",
        41 => "Backquote",
        42 => "ShiftLeft",
        43 => "Backslash",
        44 => "KeyZ",
        45 => "KeyX",
        46 => "KeyC",
        47 => "KeyV",
        48 => "KeyB",
        49 => "KeyN",
        50 => "KeyM",
        51 => "Comma",
        52 => "Period",
        53 => "Slash",
        54 => "ShiftRight",
        55 => "NumpadMultiply",
        56 => "AltLeft",
        57 => "Space",
        58 => "CapsLock",
        59 => "F1",
        60 => "F2",
        61 => "F3",
        62 => "F4",
        63 => "F5",
        64 => "F6",
        65 => "F7",
        66 => "F8",
        67 => "F9",
        68 => "F10",
        69 => "NumLock",
        70 => "ScrollLock",
        71 => "Numpad7",
        72 => "Numpad8",
        73 => "Numpad9",
        74 => "NumpadSubtract",
        75 => "Numpad4",
        76 => "Numpad5",
        77 => "Numpad6",
        78 => "NumpadAdd",
        79 => "Numpad1",
        80 => "Numpad2",
        81 => "Numpad3",
        82 => "Numpad0",
        83 => "NumpadDecimal",
        86 => "IntlBackslash",
        87 => "F11",
        88 => "F12",
        89 => "IntlRo",
        92 => "Convert",
        93 => "KanaMode",
        94 => "NonConvert",
        96 => "NumpadEnter",
        97 => "ControlRight",
        98 => "NumpadDivide",
        99 => "PrintScreen",
        100 => "AltRight",
        102 => "Home",
        103 => "ArrowUp",
        104 => "PageUp",
        105 => "ArrowLeft",
        106 => "ArrowRight",
        107 => "End",
        108 => "ArrowDown",
        109 => "PageDown",
        110 => "Insert",
        111 => "Delete",
        113 => "AudioVolumeMute",
        114 => "AudioVolumeDown",
        115 => "AudioVolumeUp",
        117 => "NumpadEqual",
        119 => "Pause",
        121 => "NumpadComma",
        124 => "IntlYen",
        125 => "MetaLeft",
        126 => "MetaRight",
        127 => "ContextMenu",
        163 => "MediaTrackNext",
        164 => "MediaPlayPause",
        165 => "MediaTrackPrevious",
        166 => "MediaStop",
        183 => "F13",
        184 => "F14",
        185 => "F15",
        186 => "F16",
        187 => "F17",
        188 => "F18",
        189 => "F19",
        190 => "F20",
        191 => "F21",
        192 => "F22",
        193 => "F23",
        194 => "F24",
        _ => UNIDENTIFIED,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// Every key on a full-size ANSI keyboard that the heatmap draws.
    const ANSI: &[&str] = &[
        "Escape",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "F11",
        "F12",
        "Backquote",
        "Digit1",
        "Digit2",
        "Digit3",
        "Digit4",
        "Digit5",
        "Digit6",
        "Digit7",
        "Digit8",
        "Digit9",
        "Digit0",
        "Minus",
        "Equal",
        "Backspace",
        "Tab",
        "KeyQ",
        "KeyW",
        "KeyE",
        "KeyR",
        "KeyT",
        "KeyY",
        "KeyU",
        "KeyI",
        "KeyO",
        "KeyP",
        "BracketLeft",
        "BracketRight",
        "Backslash",
        "CapsLock",
        "KeyA",
        "KeyS",
        "KeyD",
        "KeyF",
        "KeyG",
        "KeyH",
        "KeyJ",
        "KeyK",
        "KeyL",
        "Semicolon",
        "Quote",
        "Enter",
        "ShiftLeft",
        "KeyZ",
        "KeyX",
        "KeyC",
        "KeyV",
        "KeyB",
        "KeyN",
        "KeyM",
        "Comma",
        "Period",
        "Slash",
        "ShiftRight",
        "ControlLeft",
        "MetaLeft",
        "AltLeft",
        "Space",
        "AltRight",
        "MetaRight",
        "ContextMenu",
        "ControlRight",
        "Insert",
        "Home",
        "PageUp",
        "Delete",
        "End",
        "PageDown",
        "ArrowUp",
        "ArrowLeft",
        "ArrowDown",
        "ArrowRight",
        "NumLock",
        "NumpadDivide",
        "NumpadMultiply",
        "NumpadSubtract",
        "Numpad7",
        "Numpad8",
        "Numpad9",
        "NumpadAdd",
        "Numpad4",
        "Numpad5",
        "Numpad6",
        "Numpad1",
        "Numpad2",
        "Numpad3",
        "NumpadEnter",
        "Numpad0",
        "NumpadDecimal",
    ];
    /// Keys a standard Mac keyboard does not have.
    const NOT_ON_MAC: &[&str] = &["ContextMenu", "PrintScreen", "ScrollLock", "Pause"];

    fn covered(codes: impl Iterator<Item = &'static str>) -> HashSet<&'static str> {
        codes.filter(|c| *c != UNIDENTIFIED).collect()
    }

    #[test]
    fn mac_covers_ansi_keyboard() {
        let mac_codes = covered((0u16..=0x7F).map(mac));
        for key in ANSI.iter().filter(|k| !NOT_ON_MAC.contains(k)) {
            assert!(mac_codes.contains(key), "mac is missing {key}");
        }
    }

    #[test]
    fn windows_covers_ansi_keyboard() {
        let codes = covered(
            (0u32..=0x7F)
                .flat_map(|s| [(s, false), (s, true)])
                .filter_map(|(s, e)| windows(s, e, 0)),
        );
        for key in ANSI {
            assert!(codes.contains(key), "windows is missing {key}");
        }
    }

    #[test]
    fn evdev_covers_ansi_keyboard() {
        let codes = covered((0u32..=255).map(evdev));
        for key in ANSI {
            assert!(codes.contains(key), "evdev is missing {key}");
        }
    }

    #[test]
    fn mac_samples() {
        assert_eq!(mac(0x00), "KeyA");
        assert_eq!(mac(0x31), "Space");
        assert_eq!(mac(0x37), "MetaLeft");
        assert_eq!(mac(0x7E), "ArrowUp");
        assert_eq!(mac(0x34), UNIDENTIFIED);
    }

    #[test]
    fn windows_extended_keys_differ() {
        assert_eq!(windows(0x1C, false, 0x0D), Some("Enter"));
        assert_eq!(windows(0x1C, true, 0x0D), Some("NumpadEnter"));
        assert_eq!(windows(0x48, false, 0x68), Some("Numpad8"));
        assert_eq!(windows(0x48, true, 0x26), Some("ArrowUp"));
        assert_eq!(windows(0x36, true, 0xA1), Some("ShiftRight"));
    }

    #[test]
    fn windows_ambiguous_keys_use_virtual_key() {
        assert_eq!(windows(0x45, false, 0x13), Some("Pause"));
        assert_eq!(windows(0x45, true, 0x90), Some("NumLock"));
        assert_eq!(windows(0x37, true, 0x2C), Some("PrintScreen"));
    }

    #[test]
    fn windows_fake_shift_is_ignored() {
        assert_eq!(windows(0x2A, true, 0xA0), None);
        assert_eq!(windows(0x2A, false, 0xA0), Some("ShiftLeft"));
    }

    #[test]
    fn evdev_samples() {
        assert_eq!(evdev(30), "KeyA");
        assert_eq!(evdev(125), "MetaLeft");
        assert_eq!(evdev(0), UNIDENTIFIED);
    }
}
